config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :members, only: %i[new create show edit update destroy] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/searchable.rb
# frozen_string_literal: true

# Concern to provide search method
module Searchable
  extend ActiveSupport::Concern

  class_methods do
    def find_with_any_column(arg)
      where(build_query(arg))
    end

    private

    def filtered_attributes
      (column_names.to_a - %w[id member_id platform avatar created_at updated_at]).map(&:to_sym)
    end

    def build_query(arg)
      filtered_attributes.map { |attr| "#{attr} ILIKE '%#{arg}%'" }.join(') OR (')
    end
  end
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  include Searchable

  has_many :repositories, dependent: :destroy
  accepts_nested_attributes_for :repositories

  validates :name, presence: true
end

app/models/repository.rb
# frozen_string_literal: true

# Repository model layer
class Repository < ApplicationRecord
  include Searchable

  belongs_to :member

  validates :url, presence: true
  validates :url, format: { with: /\Ahttps:\/\/(github||gitlab).com\/[a-z]{1,}/i, message: :error }

  before_save :fetch_attributes

  enum platform: { github: 0 }

  private

  def fetch_attributes
    clear_old_repositories
    assign_attributes(GenerateGitProfileService.call(url))
  end

  def clear_old_repositories
    member.repositories.destroy_all
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# This controller is used to serve as an 'entry point' to the system
class HomeController < ApplicationController
  def index; end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

# Controller for Members CRUD
class MembersController < ApplicationController
  before_action :fetch_member, only: %i[show edit update destroy]
  def new
    @member = Member.new
    @member.repositories.build
  end

  def create
    @member = Member.new(member_params)

    return redirect_to @member, notice: build_notice(act: 'created', model: @member) if @member.save

    flash.now[:alert] = @member.errors.full_messages.to_sentence
    render :new
  end

  def show
    @repository = @member.repositories.first
  end

  def edit; end

  def update
    return redirect_to @member, notice: build_notice(act: 'updated', model: @member) if @member.update(member_params)

    @member.repositories = [@member.repositories.first] if @member.repositories.any?
    flash.now[:alert] = @member.errors.full_messages.to_sentence
    render :edit
  end

  def destroy
    redirect_to root_path, notice: build_notice(act: 'destroyed', model: @member) if @member.destroy
  end

  def search
    members = Member.find_with_any_column(search_params[:arg])
    repositories = Repository.find_with_any_column(search_params[:arg])
    @members = (members + repositories.map(&:member)).uniq
  end

  private

  def member_params
    params.require(:member).permit(:name, repositories_attributes: %i[url])
  end

  def search_params
    params.require(:search).permit(:arg)
  end

  def fetch_member
    @member = Member.find(params[:id])
  end

  def build_notice(**args)
    t("activerecord.successful.messages.#{args[:act]}",
      model: args[:model].model_name.human)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Module for application helpers
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Git Profile</h2>

<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Sed viverra libero purus, dignissim mattis nibh finibus vel.
  Nullam rutrum mattis purus, in iaculis nunc eleifend id.
  Proin vehicula rhoncus velit et aliquet.
  Maecenas ligula eros, eleifend vitae erat vitae, lobortis ultricies nisl.
  Nullam sed lacus egestas, iaculis lacus in, bibendum diam.
  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
  Fusce a ipsum nec libero gravida iaculis vel in neque.
  Curabitur arcu erat, vulputate sed turpis ut, feugiat euismod erat.
  Mauris vitae purus pulvinar, porta ligula non, cursus risus.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Cras tincidunt massa vitae ante sodales venenatis.
</p>

<p>
  Aenean tellus sem, vulputate eget est nec, sagittis laoreet mi.
  Proin eu iaculis ipsum.
  In id ante scelerisque, condimentum sem a, gravida dolor.
  Curabitur ac ultricies tellus, ut tempor orci.
  Proin mauris nulla, interdum et placerat ac, consequat sed nisi.
  Nam sed porttitor tortor, ut feugiat nibh.
  Etiam dictum nibh vitae est consequat ullamcorper.
  Praesent at enim id orci viverra mattis a non est.
  Quisque in mi pellentesque, tincidunt urna a, venenatis arcu.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Git Profile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-dark text-white'>
    <%= render 'shared/navbar' %>
    <div class='d-flex h-100 align-items-center justify-content-center row bg'>
      <main class='col-11 col-md-10 col-lg-10 p-5 mt-5 mb-5 bg-white text-dark rounded'>
        <div class="d-flex flex-column justify-content-end align-items-center">
          <%= render 'shared/messages' %>
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with model: member, local: true do |form| %>
  <div>
    <%= form.label :name, member.class.human_attribute_name(:name) %>
    <p>
      <%= form.text_field :name %>
    </p>
  </div>

  <%= form.fields_for :repositories, member.repositories do |repository_form| %>
    <div>
      <%= repository_form.label :url, 'URL' %>
      <p>
        <%= repository_form.text_field :url %>
      </p>
    </div>
  <% end %>


  <%= form.submit %>
<% end %>

app/views/members/_member.html.erb
<div class="my-1">
  <img class="avatar_thumb" src="<%= member.repositories.first.avatar %>" alt="">
  <%= link_to "#{Member.model_name.human}: #{member.name}", member %> | 
  <%= link_to Repository.model_name.human, member.repositories.first.url %>
</div>

app/views/members/edit.html.erb
<h2><%= t("#{action_name}") %> <%= @member.model_name.human %></h2>

<%= render 'form', member: @member %>

app/views/members/new.html.erb
<h2><%= t("#{action_name}") %> <%= @member.model_name.human %></h2>

<%= render 'form', member: @member %>

app/views/members/search.html.erb
<h2><%= t("#{action_name}") %></h2>

<% if @members.any? %>
  <div class="d-flex align-items-start justify-content-center row">
    <%= render @members %>
  </div>
<% end %>

app/views/members/show.html.erb
<h2><%= t("#{action_name}") %> <%= @member.model_name.human %></h2>


<p>
  <%= @member.class.human_attribute_name(:name) %>: <strong><%= @member.name %></strong>
</p>

<img class="avatar" src="<%= @repository.avatar %>" alt="">

<p>
  <%= @repository.class.human_attribute_name(:user_name) %>: <strong><%= @repository.user_name %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:user_nickname) %>: <strong><%= @repository.user_nickname %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:followers) %>: <strong><%= @repository.followers %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:following) %>: <strong><%= @repository.following %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:stars) %>: <strong><%= @repository.stars %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:last_year_contrib) %>: <strong><%= @repository.last_year_contrib %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:location) %>: <strong><%= @repository.location %></strong>
</p>
<p>
  <%= @repository.class.human_attribute_name(:organization) %>: <strong><%= @repository.organization %></strong>
</p>

<p>
  <%= link_to t(:edit), edit_member_path(@member) %> | 
  <%= link_to t(:destroy), member_path(@member), method: :delete %>
</p>

app/views/shared/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Git Profile</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"><%= t '.home' %></a>
        </li>
        <li class="nav-item">
          <%= link_to t('.add_git_profile'), new_member_path ,class: "nav-link active" %>
        </li>
      </ul>

      <%= form_with id: 'search_field', class: 'd-flex', url: search_members_path, local: true, method: :get do |f| %>
        <%= fields_for :search do |search_field| %>
          <%= search_field.text_field :arg, class: 'form-control me-2', placeholder: t('.search') %>
          <%= search_field.submit t('.search'), class: 'btn btn-outline-success', disable_with: 'Submiting...' %>
        <% end %>
      <% end %>

    </div>
  </div>
</nav>